[package]
name = "remed"
version = "1.0.0"
authors = []

[addresses]
remed_addr='0xb289ca0db88599a6f7f952621b674aeeb2c7080696a887c6bc3d480ea354f510'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
