[package]
name = "remed"
version = "1.0.0"
authors = []

[addresses]
remed_addr='0x63120a4547c03eb3114345181ede867be88b7d75acbbbeb337fbb84b958d75a4'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
